version: '3.9'

services:
  redis-internal:
    image: redis:latest
    container_name: redis-internal
    restart: always
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arbitrage-sync
    restart: always
    env_file:
      - .env
    depends_on:
      - redis-internal
    volumes:
      - ./data.db:/app/data.db
    environment:
      - CHROME_BIN=/usr/lib/chromium/chromium
