services:
  redis-internal:
    image: redis:7-alpine
    container_name: redis-internal
    restart: unless-stopped
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: arbitrage-sync-bot:local
    container_name: arbitrage-sync
    restart: unless-stopped
    depends_on:
      - redis-internal
    env_file:
      - .env
    environment:
      - CHROME_BIN=/usr/bin/chromium
    shm_size: "1gb"
    volumes:
      - ./data.db:/app/data.db:rw
